usethis::use_mit_license(name="Ludovic Crochard")
usethis::use_git()
usethis::use_roxygen_md()
usethis::use_package_doc()
devtools::document()
usethis::use_r("int_an_eff")
devtools::document()
usethis::use_package(package = "magrittr")
usethis::use_package(package = "stats")
compo_new<-read.csv("compo_new.csv")
usethis::use_data(compo_new, internal=FALSE)
usethis::use_r("compo_new")
devtools::document()
devtools::check()
usethis::use_readme_rmd()
rmarkdown::render("README.Rmd")
usethis::use_git_ignore("README.html")
devtools::document()
devtools::check()
